## FOR PROD

FROM python:3.8.2-slim-buster as builder

LABEL maintainer "Ercan Cavusoglu <ercancavusoglu@yandex.com>"

# install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc python3-pip python3-dev python3-setuptools build-essential libssl-dev libffi-dev

COPY requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip3 install -r requirements.txt

COPY . /app

CMD ["gunicorn", "--bind", ":5000", "--workers", "3", "wsgi:app"]
